<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Drawing\Utils\Interface\" />
    <Folder Include="Drawing\Utils\Abstract\" />
    <Folder Include="Drawing\Shapes\" />
    <Folder Include="DSL\" />
    <Folder Include="Drawing\Graphing\" />
  </ItemGroup>

</Project>
